/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: lucasalic99 (https://sketchfab.com/lucasalic99)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-computer-mouse-and-keyboard-low-poly-a41e98d3650e4d8ba544b6a589f3f4f3
title: Old Computer, Mouse and Keyboard Low Poly
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
    const { nodes, materials } = useGLTF("/scene.glb");
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[-1.32, 0.74, -0.16]}
                        scale={[0.67, 0.77, 0.77]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_4.geometry}
                            material={materials["Material.007"]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_5.geometry}
                            material={materials["Material.008"]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_6.geometry}
                            material={materials["Material.006"]}
                        />
                    </group>
                    <group
                        position={[-0.12, 0.05, 1.18]}
                        rotation={[0, 0.04, 0]}
                        scale={[0.12, 0.02, 0.2]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_8.geometry}
                            material={materials["Material.007"]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_9.geometry}
                            material={materials["Material.008"]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_10.geometry}
                            material={materials["Material.009"]}
                        />
                    </group>
                    <group
                        position={[-0.18, 0.06, 1.18]}
                        rotation={[0, -0.12, 0]}
                        scale={[0.13, 0.02, 0.22]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_12.geometry}
                            material={materials["Material.007"]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_13.geometry}
                            material={materials["Material.009"]}
                        />
                    </group>
                    <group
                        position={[-1.32, 0.74, -0.16]}
                        scale={[0.67, 0.77, 0.77]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_15.geometry}
                            material={materials["Material.006"]}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/scene.glb");
